{{ dbt_date.get_date_dimension("2022-01-01", "2023-01-01") }}
UNION ALL
SELECT  DATE '9999-12-31' AS date_day,
        NULL AS prior_date_day,
        NULL AS next_date_day,
        NULL AS prior_year_date_day,
        NULL AS prior_year_over_year_date_day,
        NULL AS day_of_week,
        NULL AS day_of_week_iso,
        NULL AS day_of_week_name,
        NULL AS day_of_week_name_short,
        NULL AS day_of_month,
        NULL AS day_of_year,
        NULL AS week_start_date,
        NULL AS week_end_date,
        NULL AS prior_year_week_start_date,
        NULL AS prior_year_week_end_date,
        NULL AS week_of_year,
        NULL AS iso_week_start_date,
        NULL AS iso_week_end_date,
        NULL AS prior_year_iso_week_start_date,
        NULL AS prior_year_iso_week_end_date,
        NULL AS iso_week_of_year,
        NULL AS prior_year_week_of_year,
        NULL AS prior_year_iso_week_of_year,
        NULL AS month_of_year,
        NULL AS month_name,
        NULL AS month_name_short,
        NULL AS month_start_date,
        NULL AS month_end_date,
        NULL AS prior_year_month_start_date,
        NULL AS prior_year_month_end_date,
        NULL AS quarter_of_year,
        NULL AS quarter_start_date,
        NULL AS quarter_end_date,
        NULL AS year_number,
        NULL AS year_start_date,
        NULL AS year_end_date