willibald_dwh:
  target: dev
  outputs:
    dev:
      type: databricks
      schema: willibald
      host: dbc-30dfc2de-0f3a.cloud.databricks.com
      http_path: /sql/1.0/warehouses/d1ea857c635f2f13
      token: "{{ env_var('DATABRICKS_TOKEN') }}"

    prod:
      type: databricks
      schema: willibald
      host: dbc-30dfc2de-0f3a.cloud.databricks.com
      http_path: /sql/1.0/warehouses/d1ea857c635f2f13
      token: "{{ env_var('DATABRICKS_TOKEN') }}"
